Resources:
 EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
   AvailabilityZone: ap-south-1a
   ImageId: ami-001843b876406202a
   InstanceType: t2.micro
   KeyName: dbserver
   Tags:
    - Key: Name
      Value: Webserver
   UserData:
    Fn::Base64: !Sub |
      #!/bin/bash
      sudo apt-get update -y
      sudo apt-get install openjdk-11-jdk -y
      sudo apt-get install -y jenkins
      java-jar jenkins.war
      sudo apt-get install -y nginx
      service nginx start
